[package]
name = "localstorage"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.15", features = ["js"] }
leptos = { version = "0.7.0", features = ["csr"] }
leptos_router = "0.7.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
web-sys = { version = "0.3.74", features = ["Storage", "Window"] }
